package newtimes.production.process.order_change;
import java.util.*;
import newtimes.production.process.prodmaintain.DB_ColorSizeQtyHandler;

public class ProxyQtyHdl extends DB_ColorSizeQtyHandler {
  public boolean isUsingProxy=false;
  private newtimesejb.production.OrderChangeFacade changeQtyFacade;
  protected java.util.Vector myClrLxyPrxs;
  protected java.util.HashMap myPRX_ClrLxyPrx;
  public ProxyQtyHdl() {
    //this.Prices=getPriceRecords();
    //super();
    try{
      newtimesejb.production.OrderChangeFacadeHome chgFdHome=
          (newtimesejb.production.OrderChangeFacadeHome)
          info_ejb.WeblogicServiceLocator.locateServiceHome(
          util.PublicVariable.SERVER_URL,"newtimesejb.production.OrderChangeFacade");
      changeQtyFacade=chgFdHome.create();
      //prepare for prxy need.
      /*
      super.ClrLixPrx is generated by:
      select a.pri_seq,a.PRI_BYR_ACT_PRX,
      (select b.PROD_COLOR_name from prod_color b where b.PROD_COLOR_PK=a.PROD_COLOR_PK) as color_name,
      (select c.BYMKR_BRIEF from buyer_maker c where c.BYMKR_SEQ=a.PRI_LICENSEE_NAME) as licensee
      from price a where  a.record_delete_flag='1' and a.pri_sty_seq=67
      */
      database.datatype.Record recTmp=
          (database.datatype.Record)ClrLixPrx.get(0);
      myPRX_ClrLxyPrx=new java.util.HashMap();
      String[] pxy_prx_stored_data=
             tempDataCenter.str_arr_NEW_LXY_CLR_PRX_PRI_SEQ_data;
                                        //LXY,CLR,PRX,price_seq
      myClrLxyPrxs=new Vector();
      //for(int i=0;i<ClrLixPrx.size();i++){
      for(int i=0;i<pxy_prx_stored_data.length;i++){
        database.datatype.Record newRec=
            (database.datatype.Record)util.MiscFunc.deepCopy(recTmp);
        String[] aRow=
            util.MiscFunc.split(pxy_prx_stored_data[i],
            tempDataCenter.Splet4str_arr_NEW_PRI_SEQ_LXY_CLR_PRX_data);
       System.out.println(" pxy_prx_stored_data["+i+"]:"+pxy_prx_stored_data[i]);
        newRec.set(0,new java.math.BigDecimal(aRow[3]));//pri_seq,
        //be ware of Type identification for "equals" method of "exgui.ultratable.Wraper4tblCbx" class
        //will be compared while layout to combobox
        newRec.set(1,aRow[2]);//price
        newRec.set(2,aRow[1]);//color_name
        newRec.set(3,aRow[0]);//licensee
        newRec.set(4,aRow[0]+"/"+aRow[1]);//licensee_color_name
        myClrLxyPrxs.add(newRec);

        myPRX_ClrLxyPrx.put(aRow[3],aRow[2]);
      }
    }catch(Exception e){
      e.printStackTrace();
      exgui.verification.VerifyLib.showAlert(
          "Server Side Error\nPlease Notify SystemManager","EJB Creation Error");
      util.ExceptionLog.exp2File(e,"Error while lookup qty change handler");
      super.isInitOk=false;
    }
  }
  public java.util.HashMap getPriSeqMapPrx(){
    if(isUsingProxy) {
      return myPRX_ClrLxyPrx;
    }
    return  super.PRX_ClrLxyPrx;
  }
  public Vector getClrLxyPrxs(){
    if(isUsingProxy){
      return myClrLxyPrxs;
    }
    return super.ClrLixPrx;
  }
  public Vector getPriceRecords(){
    if(!isUsingProxy )return super.Prices;
    if(newtimes.production.process.order_change.tempDataCenter.STORED_CHG_PRX_RECORDS==null||
       newtimes.production.process.order_change.tempDataCenter.STORED_CHG_PRX_RECORDS.size()==0
     )return super.Prices;
    return newtimes.production.process.order_change.tempDataCenter.STORED_CHG_PRX_RECORDS;
  }
  public void finalConfirmUpdate()throws Exception{
    changeQtyFacade.updateOrderChange(
        (String)util.PublicVariable.USER_RECORD.get("usr_code"),
        newtimes.production.process.order_change.tempDataCenter.tempStoredChangeStyleData,
        newtimes.production.process.order_change.tempDataCenter.STORED_CHG_PRX_RECORDS,
        newtimes.production.process.order_change.tempDataCenter.FinalChangedQtyRecords,
        (String)
        newtimes.production.process.order_change.tempDataCenter.tempStoredChangeStyleData.get(
        "sty_qty_desc"));
      //after update,clear vector
       newtimes.production.process.order_change.tempDataCenter.tempStoredChangeStyleData=null;
       newtimes.production.process.order_change.tempDataCenter.STORED_CHG_PRX_RECORDS=null;
       newtimes.production.process.order_change.tempDataCenter.FinalChangedQtyRecords=null;

  }
  public void updateRecords(Vector vct2update,String updateQtyTbl2Text)throws Exception{
    newtimes.production.process.order_change.tempDataCenter.tempStoredChangeStyleData.set(
      "sty_qty_desc",updateQtyTbl2Text);
    newtimes.production.process.order_change.tempDataCenter.FinalChangedQtyRecords=
        vct2update;
  }
}
