package newtimes.basic.size;

import java.awt.*;
import newtimes.*;
import javax.swing.*;
import java.awt.event.*;

/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class SizeAdd extends JPanel {
  Frame1 frame;
  private JLabel textAreaStatus = new JLabel();
  private JButton butnAdd = new JButton();
  private JLabel jLabel1 = new JLabel();
  private JButton butnExit = new JButton();
  private JTextField txtS7 = new JTextField();
  private JTextField txtS2 = new JTextField();
  private JTextField txtS1 = new JTextField();
  private JTextField txtS4 = new JTextField();
  private JTextField txtS8 = new JTextField();
  private JTextField txtS5 = new JTextField();
  private JTextField txtS6 = new JTextField();
  private JTextField txtS3 = new JTextField();
  private JLabel jTextField2 = new JLabel();
  private JLabel jTextField3 = new JLabel();
  private JLabel jTextField4 = new JLabel();
  private JLabel jTextField5 = new JLabel();
  private JLabel jTextField6 = new JLabel();
  private JLabel jTextField7 = new JLabel();
  private JLabel jTextField8 = new JLabel();
  private JLabel jTextField9 = new JLabel();
  private JLabel jTextField10 = new JLabel();
  private JLabel jTextField11 = new JLabel();
  private JLabel jTextField12 = new JLabel();
  private JLabel jTextField13 = new JLabel();
  private JLabel jTextField14 = new JLabel();
  private JLabel jTextField15 = new JLabel();
  private JLabel jTextField16 = new JLabel();
  private JLabel jTextField17 = new JLabel();
  private JLabel jTextField18 = new JLabel();
  private JLabel jTextField19 = new JLabel();
  private JLabel jTextField110 = new JLabel();
  private JLabel jTextField111 = new JLabel();
  private JLabel jTextField112 = new JLabel();
  private JLabel jTextField113 = new JLabel();
  private JLabel jTextField114 = new JLabel();
  private JLabel jTextField115 = new JLabel();
  private JTextField txtS9 = new JTextField();
  private JTextField txtS10 = new JTextField();
  private JTextField txtS11 = new JTextField();
  private JTextField txtS12 = new JTextField();
  private JTextField txtS13 = new JTextField();
  private JTextField txtS14 = new JTextField();
  private JTextField txtS15 = new JTextField();
  private JTextField txtS16 = new JTextField();
  private JTextField txtS23 = new JTextField();
  private JTextField txtS18 = new JTextField();
  private JTextField txtS19 = new JTextField();
  private JTextField txtS20 = new JTextField();
  private JTextField txtS24 = new JTextField();
  private JTextField txtS21 = new JTextField();
  private JTextField txtS22 = new JTextField();
  private JTextField txtS17 = new JTextField();
  java.util.HashMap hm2CheckDup=new java.util.HashMap();
  public SizeAdd(Frame1 _frame) {
    frame = _frame;
    try {
      jbInit();
    }
    catch(Exception ex) {
      ex.printStackTrace();
    }
  }
  void jbInit() throws Exception {
    this.setMaxLength();
    butnExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        butnExit_actionPerformed(e);
      }
    });
    butnExit.setText("Exit");
    butnExit.setForeground(Color.darkGray);
    butnExit.setFont(new java.awt.Font("Dialog", 1, 13));
    butnExit.setBounds(new Rectangle(395, 480, 80, 25));
    butnExit.setBackground(Color.lightGray);
    jLabel1.setBounds(new Rectangle(117, 26, 566, 24));
    jLabel1.setText("      ============  Size Add  ============      ");
    jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
    jLabel1.setBorder(BorderFactory.createEtchedBorder());
    jLabel1.setForeground(new Color(10,36,106));
    jLabel1.setFont(new java.awt.Font("Dialog", 1, 13));
    butnAdd.setText("Add");
    butnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        butnAdd_actionPerformed(e);
      }
    });
    butnAdd.setForeground(Color.darkGray);
    butnAdd.setFont(new java.awt.Font("Dialog", 1, 13));
    butnAdd.setBounds(new Rectangle(301, 480, 80, 25));
    butnAdd.setBackground(Color.lightGray);
    textAreaStatus.setBounds(new Rectangle(0, 540, 800, 30));
    //textAreaStatus.setEditable(false);
    textAreaStatus.setOpaque(true);
    textAreaStatus.setBorder(null);
    textAreaStatus.setBackground(new Color(143, 143, 188));
    this.setLayout(null);
    this.setSize(800,600);
    this.setBackground(new Color(204, 204, 225));
    txtS7.setBackground(Color.white);
    txtS7.setForeground(new Color(10,36,106));
    //txtS7.setNextFocusableComponent(txtS8);
    txtS7.setDisabledTextColor(Color.gray);
    txtS7.setBounds(new Rectangle(479, 172, 59, 18));
    txtS2.setBackground(Color.white);
    txtS2.setForeground(new Color(10,36,106));
    //txtS2.setNextFocusableComponent(txtS3);
    txtS2.setDisabledTextColor(Color.gray);
    txtS2.setBounds(new Rectangle(105, 172, 59, 18));
    txtS1.setBackground(Color.white);
    txtS1.setForeground(new Color(10,36,106));
    //txtS1.setNextFocusableComponent(txtS2);
    txtS1.setDisabledTextColor(Color.gray);
    txtS1.setBounds(new Rectangle(29, 172, 59, 18));
    txtS4.setBackground(Color.white);
    txtS4.setForeground(new Color(10,36,106));
//    txtS4.setNextFocusableComponent(txtS5);
    txtS4.setDisabledTextColor(Color.gray);
    txtS4.setBounds(new Rectangle(256, 172, 59, 18));
    txtS8.setBackground(Color.white);
    txtS8.setForeground(new Color(10,36,106));
    txtS8.setDisabledTextColor(Color.gray);
    txtS8.setBounds(new Rectangle(553, 172, 59, 18));
    txtS5.setBackground(Color.white);
    txtS5.setForeground(new Color(10,36,106));
//    txtS5.setNextFocusableComponent(txtS6);
    txtS5.setDisabledTextColor(Color.gray);
    txtS5.setBounds(new Rectangle(331, 172, 59, 18));
    txtS6.setBackground(Color.white);
    txtS6.setForeground(new Color(10,36,106));
//    txtS6.setNextFocusableComponent(txtS7);
    txtS6.setDisabledTextColor(Color.gray);
    txtS6.setBounds(new Rectangle(405, 172, 59, 18));
    txtS3.setBackground(Color.white);
    txtS3.setForeground(new Color(10,36,106));
//    txtS3.setNextFocusableComponent(txtS4);
    txtS3.setDisabledTextColor(Color.gray);
    txtS3.setBounds(new Rectangle(181, 172, 59, 18));
    txtS7.setBounds(new Rectangle(559, 122, 59, 23));
    txtS2.setBounds(new Rectangle(185, 122, 59, 23));
    txtS1.setBounds(new Rectangle(109, 122, 59, 23));
    txtS4.setBounds(new Rectangle(336, 122, 59, 23));
    txtS8.setBounds(new Rectangle(633, 122, 59, 23));
    txtS5.setBounds(new Rectangle(411, 122, 59, 23));
    txtS6.setBounds(new Rectangle(485, 122, 59, 23));
    txtS3.setBounds(new Rectangle(261, 122, 59, 23));
    jTextField2.setBounds(new Rectangle(109, 97, 59, 23));
    jTextField2.setText("        1");
    jTextField2.setBorder(null);
    jTextField2.setOpaque(true);
    //jTextField2.setEditable(false);
    jTextField2.setForeground(new Color(10,36,106));
    jTextField2.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField2.setBackground(new Color(143, 143, 188));
    jTextField3.setBackground(new Color(143, 143, 188));
    jTextField3.setForeground(Color.white);
    jTextField3.setOpaque(true);
    //jTextField3.setEditable(false);
    jTextField3.setBorder(null);
    jTextField3.setText("        2");
    jTextField3.setBounds(new Rectangle(185, 97, 59, 23));
    jTextField4.setBackground(new Color(143, 143, 188));
    jTextField4.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField4.setForeground(new Color(10,36,106));
    jTextField4.setOpaque(true);
    //jTextField4.setEditable(false);
    jTextField4.setBorder(null);
    jTextField4.setText("        3");
    jTextField4.setBounds(new Rectangle(261, 97, 59, 23));
    jTextField5.setBackground(new Color(143, 143, 188));
    jTextField5.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField5.setForeground(Color.white);
    jTextField5.setOpaque(true);
    //jTextField5.setEditable(false);
    jTextField5.setBorder(null);
    jTextField5.setText("        4");
    jTextField5.setBounds(new Rectangle(336, 97, 59, 23));
    jTextField6.setBackground(new Color(143, 143, 188));
    jTextField6.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField6.setForeground(new Color(10,36,106));
    jTextField6.setOpaque(true);
    //jTextField6.setEditable(false);
    jTextField6.setBorder(null);
    jTextField6.setText("        5");
    jTextField6.setBounds(new Rectangle(411, 97, 59, 23));
    jTextField7.setBackground(new Color(143, 143, 188));
    jTextField7.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField7.setForeground(Color.white);
    jTextField7.setOpaque(true);
   // jTextField7.setEditable(false);
    jTextField7.setBorder(null);
    jTextField7.setText("        6");
    jTextField7.setBounds(new Rectangle(485, 97, 59, 23));
    jTextField8.setBackground(new Color(143, 143, 188));
    jTextField8.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField8.setForeground(new Color(10,36,106));
    //jTextField8.setEditable(false);
    jTextField8.setBorder(null);
    jTextField8.setText("       7");
    jTextField8.setBounds(new Rectangle(559, 97, 59, 23));
    jTextField8.setOpaque(true);
    jTextField9.setBackground(new Color(143, 143, 188));
    jTextField9.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField9.setForeground(Color.white);
    jTextField9.setOpaque(true);
   // jTextField9.setEditable(false);
    jTextField9.setBorder(null);
    jTextField9.setText("        8");
    jTextField9.setBounds(new Rectangle(633, 97, 59, 23));
    jTextField10.setBackground(new Color(143, 143, 188));
    jTextField10.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField10.setForeground(new Color(10,36,106));
    jTextField10.setOpaque(true);
    //jTextField10.setEditable(false);
    jTextField10.setBorder(null);
    jTextField10.setText("        9");
    jTextField10.setBounds(new Rectangle(109, 170, 59, 23));
    jTextField11.setBackground(new Color(143, 143, 188));
    jTextField11.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField11.setForeground(Color.white);
    jTextField11.setOpaque(true);
    //jTextField11.setEditable(false);
    jTextField11.setBorder(null);
    jTextField11.setText("       10");
    jTextField11.setBounds(new Rectangle(185, 170, 59, 23));
    jTextField12.setBackground(new Color(143, 143, 188));
    jTextField12.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField12.setForeground(new Color(10,36,106));
    jTextField12.setOpaque(true);
    //jTextField12.setEditable(false);
    jTextField12.setBorder(null);
    jTextField12.setText("       11");
    jTextField12.setBounds(new Rectangle(261, 170, 59, 23));
    jTextField13.setBackground(new Color(143, 143, 188));
    jTextField13.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField13.setForeground(Color.white);
    jTextField13.setOpaque(true);
    //jTextField13.setEditable(false);
    jTextField13.setBorder(null);
    jTextField13.setText("       12");
    jTextField13.setBounds(new Rectangle(336, 170, 59, 23));
    jTextField14.setBackground(new Color(143, 143, 188));
    jTextField14.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField14.setForeground(new Color(10,36,106));
    jTextField14.setOpaque(true);
    //jTextField14.setEditable(false);
    jTextField14.setBorder(null);
    jTextField14.setText("       13");
    jTextField14.setBounds(new Rectangle(411, 170, 59, 23));
    jTextField15.setBackground(new Color(143, 143, 188));
    jTextField15.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField15.setForeground(Color.white);
    jTextField15.setOpaque(true);
    //jTextField15.setEditable(false);
    jTextField15.setBorder(null);
    jTextField15.setText("       14");
    jTextField15.setBounds(new Rectangle(485, 170, 59, 23));
    jTextField16.setBackground(new Color(143, 143, 188));
    jTextField16.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField16.setForeground(new Color(10,36,106));
    jTextField16.setOpaque(true);
    //jTextField16.setEditable(false);
    jTextField16.setBorder(null);
    jTextField16.setText("       15");
    jTextField16.setBounds(new Rectangle(559, 170, 59, 23));
    jTextField17.setBackground(new Color(143, 143, 188));
    jTextField17.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField17.setForeground(Color.white);
    jTextField17.setOpaque(true);
    //jTextField17.setEditable(false);
    jTextField17.setBorder(null);
    jTextField17.setText("       16");
    jTextField17.setBounds(new Rectangle(633, 170, 59, 23));
    jTextField18.setBackground(new Color(143, 143, 188));
    jTextField18.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField18.setForeground(new Color(10,36,106));
    jTextField18.setOpaque(true);
    //jTextField18.setEditable(false);
    jTextField18.setBorder(null);
    jTextField18.setText("       21");
    jTextField18.setBounds(new Rectangle(411, 243, 59, 23));
    jTextField19.setBackground(new Color(143, 143, 188));
    jTextField19.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField19.setForeground(Color.white);
    jTextField19.setOpaque(true);
    //jTextField19.setEditable(false);
    jTextField19.setBorder(null);
    jTextField19.setText("       22");
    jTextField19.setBounds(new Rectangle(485, 243, 59, 23));
    jTextField110.setBackground(new Color(143, 143, 188));
    jTextField110.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField110.setForeground(new Color(10,36,106));
    jTextField110.setOpaque(true);
    //jTextField110.setEditable(false);
    jTextField110.setBorder(null);
    jTextField110.setText("       23");
    jTextField110.setBounds(new Rectangle(559, 243, 59, 23));
    jTextField111.setBackground(new Color(143, 143, 188));
    jTextField111.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField111.setForeground(Color.white);
    jTextField111.setOpaque(true);
    //jTextField111.setEditable(false);
    jTextField111.setBorder(null);
    jTextField111.setText("       24");
    jTextField111.setBounds(new Rectangle(633, 243, 59, 23));
    jTextField112.setBackground(new Color(143, 143, 188));
    jTextField112.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField112.setForeground(new Color(10,36,106));
    jTextField112.setOpaque(true);
    //jTextField112.setEditable(false);
    jTextField112.setBorder(null);
    jTextField112.setText("       17");
    jTextField112.setBounds(new Rectangle(109, 243, 59, 23));
    jTextField113.setBackground(new Color(143, 143, 188));
    jTextField113.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField113.setForeground(Color.white);
    jTextField113.setOpaque(true);
    //jTextField113.setEditable(false);
    jTextField113.setBorder(null);
    jTextField113.setText("       18");
    jTextField113.setBounds(new Rectangle(185, 243, 59, 23));
    jTextField114.setBackground(new Color(143, 143, 188));
    jTextField114.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField114.setForeground(new Color(10,36,106));
    jTextField114.setOpaque(true);
    //jTextField114.setEditable(false);
    jTextField114.setBorder(null);
    jTextField114.setText("       19");
    jTextField114.setBounds(new Rectangle(261, 243, 59, 23));
    jTextField115.setBackground(new Color(143, 143, 188));
    jTextField115.setFont(new java.awt.Font("Dialog", 1, 12));
    jTextField115.setForeground(Color.white);
    jTextField115.setOpaque(true);
    //jTextField115.setEditable(false);
    jTextField115.setBorder(null);
    jTextField115.setText("       20");
    jTextField115.setBounds(new Rectangle(336, 243, 59, 23));
    txtS9.setBounds(new Rectangle(559, 195, 59, 23));
    txtS9.setBounds(new Rectangle(109, 195, 59, 23));
    txtS9.setDisabledTextColor(Color.gray);
//    txtS9.setNextFocusableComponent(txtS13);
    txtS9.setForeground(new Color(10,36,106));
    txtS9.setBackground(Color.white);
    txtS10.setBounds(new Rectangle(185, 195, 59, 23));
    txtS10.setBounds(new Rectangle(185, 195, 59, 23));
    txtS10.setDisabledTextColor(Color.gray);
//    txtS10.setNextFocusableComponent(txtS16);
    txtS10.setForeground(new Color(10,36,106));
    txtS10.setBackground(Color.white);
    txtS11.setBounds(new Rectangle(109, 195, 59, 23));
    txtS11.setBounds(new Rectangle(261, 195, 59, 23));
    txtS11.setDisabledTextColor(Color.gray);
//    txtS11.setNextFocusableComponent(txtS10);
    txtS11.setForeground(new Color(10,36,106));
    txtS11.setBackground(Color.white);
    txtS12.setBounds(new Rectangle(336, 195, 59, 23));
    txtS12.setBounds(new Rectangle(336, 195, 59, 23));
    txtS12.setDisabledTextColor(Color.gray);
//    txtS12.setNextFocusableComponent(txtS14);
    txtS12.setForeground(new Color(10,36,106));
    txtS12.setBackground(Color.white);
    txtS13.setBounds(new Rectangle(633, 195, 59, 23));
    txtS13.setBounds(new Rectangle(411, 195, 59, 23));
    txtS13.setDisabledTextColor(Color.gray);
    txtS13.setForeground(new Color(10,36,106));
    txtS13.setBackground(Color.white);
    txtS14.setBounds(new Rectangle(411, 195, 59, 23));
    txtS14.setBounds(new Rectangle(485, 195, 59, 23));
    txtS14.setDisabledTextColor(Color.gray);
//    txtS14.setNextFocusableComponent(txtS15);
    txtS14.setForeground(new Color(10,36,106));
    txtS14.setBackground(Color.white);
    txtS15.setBounds(new Rectangle(485, 195, 59, 23));
    txtS15.setBounds(new Rectangle(559, 195, 59, 23));
    txtS15.setDisabledTextColor(Color.gray);
//    txtS15.setNextFocusableComponent(txtS9);
    txtS15.setForeground(new Color(10,36,106));
    txtS15.setBackground(Color.white);
    txtS16.setBounds(new Rectangle(261, 195, 59, 23));
    txtS16.setBounds(new Rectangle(633, 195, 59, 23));
    txtS16.setDisabledTextColor(Color.gray);
//    txtS16.setNextFocusableComponent(txtS12);
    txtS16.setForeground(new Color(10,36,106));
    txtS16.setBackground(Color.white);
    txtS23.setBounds(new Rectangle(559, 195, 59, 23));
    txtS23.setBounds(new Rectangle(559, 268, 59, 23));
    txtS23.setDisabledTextColor(Color.gray);
//    txtS23.setNextFocusableComponent(txtS24);
    txtS23.setForeground(new Color(10,36,106));
    txtS23.setBackground(Color.white);
    txtS18.setBounds(new Rectangle(185, 195, 59, 23));
    txtS18.setBounds(new Rectangle(185, 268, 59, 23));
    txtS18.setDisabledTextColor(Color.gray);
//    txtS18.setNextFocusableComponent(txtS17);
    txtS18.setForeground(new Color(10,36,106));
    txtS18.setBackground(Color.white);
    txtS19.setBounds(new Rectangle(109, 195, 59, 23));
    txtS19.setBounds(new Rectangle(261, 268, 59, 23));
    txtS19.setDisabledTextColor(Color.gray);
//    txtS19.setNextFocusableComponent(txtS18);
    txtS19.setForeground(new Color(10,36,106));
    txtS19.setBackground(Color.white);
    txtS20.setBounds(new Rectangle(336, 195, 59, 23));
    txtS20.setBounds(new Rectangle(336, 268, 59, 23));
    txtS20.setDisabledTextColor(Color.gray);
//    txtS20.setNextFocusableComponent(txtS21);
    txtS20.setForeground(new Color(10,36,106));
    txtS20.setBackground(Color.white);
    txtS24.setBounds(new Rectangle(633, 195, 59, 23));
    txtS24.setBounds(new Rectangle(633, 268, 59, 23));
    txtS24.setDisabledTextColor(Color.gray);
    txtS24.setForeground(new Color(10,36,106));
    txtS24.setBackground(Color.white);
    txtS21.setBounds(new Rectangle(411, 195, 59, 23));
    txtS21.setBounds(new Rectangle(411, 268, 59, 23));
    txtS21.setDisabledTextColor(Color.gray);
//    txtS21.setNextFocusableComponent(txtS22);
    txtS21.setForeground(new Color(10,36,106));
    txtS21.setBackground(Color.white);
    txtS22.setBounds(new Rectangle(485, 195, 59, 23));
    txtS22.setBounds(new Rectangle(485, 268, 59, 23));
    txtS22.setDisabledTextColor(Color.gray);
//    txtS22.setNextFocusableComponent(txtS23);
    txtS22.setForeground(new Color(10,36,106));
    txtS22.setBackground(Color.white);
    txtS17.setBounds(new Rectangle(261, 195, 59, 23));
    txtS17.setBounds(new Rectangle(109, 268, 59, 23));
    txtS17.setDisabledTextColor(Color.gray);
//    txtS17.setNextFocusableComponent(txtS20);
    txtS17.setForeground(new Color(10,36,106));
    txtS17.setBackground(Color.white);
    this.add(butnAdd, null);
    this.add(butnExit, null);
    this.add(textAreaStatus, null);
    this.add(jLabel1, null);
    this.add(jTextField4, null);
    this.add(jTextField2, null);
    this.add(jTextField3, null);
    this.add(jTextField5, null);
    this.add(jTextField6, null);
    this.add(jTextField7, null);
    this.add(jTextField8, null);
    this.add(jTextField9, null);
    this.add(jTextField112, null);
    this.add(jTextField113, null);
    this.add(jTextField114, null);
    this.add(jTextField115, null);
    this.add(jTextField18, null);
    this.add(jTextField19, null);
    this.add(jTextField110, null);
    this.add(jTextField111, null);
    this.add(jTextField10, null);
    this.add(jTextField11, null);
    this.add(jTextField12, null);
    this.add(jTextField13, null);
    this.add(jTextField14, null);
    this.add(jTextField15, null);
    this.add(jTextField16, null);
    this.add(jTextField17, null);


    this.add(txtS1, null);
    this.add(txtS2, null);
    this.add(txtS3, null);
    this.add(txtS4, null);
    this.add(txtS5, null);
    this.add(txtS6, null);
    this.add(txtS7, null);
    this.add(txtS8, null);
    this.add(txtS9, null);
    this.add(txtS10, null);
    this.add(txtS11, null);

    this.add(txtS12, null);
    this.add(txtS13, null);
    this.add(txtS14, null);
    this.add(txtS15, null);
    this.add(txtS16, null);
    this.add(txtS17, null);
    this.add(txtS18, null);
    this.add(txtS19, null);


    this.add(txtS20, null);
    this.add(txtS21, null);
    this.add(txtS22, null);
    this.add(txtS23, null);
    this.add(txtS24, null);




  }

  void butnExit_actionPerformed(ActionEvent e) {
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    frame.showPanel(new newtimes.basic.size.SizeList(frame));
    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
  }
  protected boolean doCheckDupSize(JTextField txt){
    if(txt.getText().trim().length()==0)return true;
    if(hm2CheckDup.containsKey(txt.getText().trim().toUpperCase())){
      exgui.verification.VerifyLib.showAlert("Size Duplicated","Size Duplicated");
      txt.grabFocus();
      txt.selectAll();
      return false;
    }
    hm2CheckDup.put(txt.getText().trim().toUpperCase(),txt.getText().trim().toUpperCase());
    return true;
  }

  void butnAdd_actionPerformed(ActionEvent e) {
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    java.util.HashMap hm = new java.util.HashMap();
    try {
      hm.put("SIZE1", txtS1.getText().trim().toUpperCase());if(!doCheckDupSize(txtS1))return;
      hm.put("SIZE2", txtS2.getText().trim().toUpperCase());if(!doCheckDupSize(txtS2))return;
      hm.put("SIZE3", txtS3.getText().trim().toUpperCase());if(!doCheckDupSize(txtS3))return;
      hm.put("SIZE4", txtS4.getText().trim().toUpperCase());if(!doCheckDupSize(txtS4))return;
      hm.put("SIZE5", txtS5.getText().trim().toUpperCase());if(!doCheckDupSize(txtS5))return;
      hm.put("SIZE6", txtS6.getText().trim().toUpperCase());if(!doCheckDupSize(txtS6))return;
      hm.put("SIZE7", txtS7.getText().trim().toUpperCase());if(!doCheckDupSize(txtS7))return;
      hm.put("SIZE8", txtS8.getText().trim().toUpperCase());if(!doCheckDupSize(txtS8))return;
      hm.put("SIZE9", txtS9.getText().trim().toUpperCase());if(!doCheckDupSize(txtS9))return;
      hm.put("SIZE10", txtS10.getText().trim().toUpperCase());if(!doCheckDupSize(txtS10))return;
      hm.put("SIZE11", txtS11.getText().trim().toUpperCase());if(!doCheckDupSize(txtS11))return;
      hm.put("SIZE12", txtS12.getText().trim().toUpperCase());if(!doCheckDupSize(txtS12))return;
      hm.put("SIZE13", txtS13.getText().trim().toUpperCase());if(!doCheckDupSize(txtS13))return;
      hm.put("SIZE14", txtS14.getText().trim().toUpperCase());if(!doCheckDupSize(txtS14))return;
      hm.put("SIZE15", txtS15.getText().trim().toUpperCase());if(!doCheckDupSize(txtS15))return;
      hm.put("SIZE16", txtS16.getText().trim().toUpperCase());if(!doCheckDupSize(txtS16))return;
      hm.put("SIZE17", txtS17.getText().trim().toUpperCase());if(!doCheckDupSize(txtS17))return;
      hm.put("SIZE18", txtS18.getText().trim().toUpperCase());if(!doCheckDupSize(txtS18))return;
      hm.put("SIZE19", txtS19.getText().trim().toUpperCase());if(!doCheckDupSize(txtS19))return;
      hm.put("SIZE20", txtS20.getText().trim().toUpperCase());if(!doCheckDupSize(txtS20))return;
      hm.put("SIZE21", txtS21.getText().trim().toUpperCase());if(!doCheckDupSize(txtS21))return;
      hm.put("SIZE22", txtS22.getText().trim().toUpperCase());if(!doCheckDupSize(txtS22))return;
      hm.put("SIZE23", txtS23.getText().trim().toUpperCase());if(!doCheckDupSize(txtS23))return;
      hm.put("SIZE24", txtS24.getText().trim().toUpperCase());if(!doCheckDupSize(txtS24))return;
      hm2CheckDup.clear();
      hm.put("create_user", util.PublicVariable.USER_RECORD.get("USR_CODE"));
      int isOk = exgui2.CONST.BASIC_MAIN_EJB.insertSize(hm);
      if (exgui2.Stuff.insertMessage(frame, isOk))
        frame.showPanel(new newtimes.basic.size.SizeList(frame));
    } catch (Exception eAdd) {
      eAdd.printStackTrace();
      util.ExceptionLog.exp2File(eAdd, "error at insert data." + hm.toString());
    }finally{
      setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }
  }

  void setMaxLength(){
    exgui.DataBindText tx = null;
    tx = new exgui.DataBindText(txtS1,null,"",10);
    tx = new exgui.DataBindText(txtS2,null,"",10);
    tx = new exgui.DataBindText(txtS3,null,"",10);
    tx = new exgui.DataBindText(txtS4,null,"",10);
    tx = new exgui.DataBindText(txtS5,null,"",10);
    tx = new exgui.DataBindText(txtS6,null,"",10);
    tx = new exgui.DataBindText(txtS7,null,"",10);
    tx = new exgui.DataBindText(txtS8,null,"",10);
    tx = new exgui.DataBindText(txtS9,null,"",10);
    tx = new exgui.DataBindText(txtS10,null,"",10);
    tx = new exgui.DataBindText(txtS11,null,"",10);
    tx = new exgui.DataBindText(txtS12,null,"",10);
    tx = new exgui.DataBindText(txtS13,null,"",10);
    tx = new exgui.DataBindText(txtS14,null,"",10);
    tx = new exgui.DataBindText(txtS15,null,"",10);
    tx = new exgui.DataBindText(txtS16,null,"",10);
    tx = new exgui.DataBindText(txtS17,null,"",10);
    tx = new exgui.DataBindText(txtS18,null,"",10);
    tx = new exgui.DataBindText(txtS19,null,"",10);
    tx = new exgui.DataBindText(txtS20,null,"",10);
    tx = new exgui.DataBindText(txtS21,null,"",10);
    tx = new exgui.DataBindText(txtS22,null,"",10);
    tx = new exgui.DataBindText(txtS23,null,"",10);
    tx = new exgui.DataBindText(txtS24,null,"",10);
  }
}
