package newtimes.production.process.prodmaintain;

import exgui.ultratable.PagedDataFactoryAdapter;
import database.datatype.Record;
/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */

public class DB_FrabricPO extends PagedDataFactoryAdapter {
  int prodHeadSeq=0;
  String xntuser=null;
  public DB_FrabricPO() {
    try{
      prodHeadSeq=newtimes.preproduction.Constants.CURRENT_PREPROD_HEAD_PK;
      newtimesejb.production.FabricPOFacadeHome ejbHome=
          (newtimesejb.production.FabricPOFacadeHome)
          info_ejb.WeblogicServiceLocator.locateServiceHome(
           util.PublicVariable.SERVER_URL,
           "newtimesejb.production.FabricPOFacade"
          );
      super.ejb=ejbHome.create();
      super.blankRecord =ejb.getBlankRecord();
      xntuser=(String)util.PublicVariable.USER_RECORD.get("USR_CODE");
      super.blankRecord.set("record_create_user",xntuser);
      super.conditions=new java.util.HashMap();
      super.conditions.put("FAB_PROD_HEAD_PK",new Integer(prodHeadSeq));
      super.conditions.put("record_delete_flag","1");
    }catch(Exception e){
      e.printStackTrace();
      exgui.verification.VerifyLib.showAlert("Server Side Exception\nPlease Notify System Manager","Conenction or EJB creation Exception");
    }
  }
  public void addRecords(java.util.Vector rec2add)throws Exception{
    ((newtimesejb.production.FabricPOFacade)ejb).addRecords(rec2add);
  }
  public Record getBlankRecord() throws Exception{
    Record rec=super.getBlankRecord();
    rec.set(1,newtimes.preproduction.Constants.CURRENT_PREPROD_HEAD_PK);
    //column 0 is generated by sequece.and column2 is by ejb to count the number of specified production seq
    return rec;
  }
  public String getFabricContent()throws Exception{
    return ((newtimesejb.production.FabricPOFacade)ejb).getFbrcContent(prodHeadSeq);
  }
  public void updateFabricContent(String str2update)throws Exception{
     ((newtimesejb.production.FabricPOFacade)ejb).updateFbrcContent(prodHeadSeq, str2update,xntuser);
  }
}
